<?php
/* Array of Elements to look for*/
$elements = array(// "iati-activity",
        //"iati-activities",
        "reporting-org",
        "other-identifier",
        "activity-status",
        "activity-date",
        "contact-info",
        "participating-org",
        "sector",
        "default-tied-status",
        "default-flow-type",
        "default-aid-type",
        "default-finance-type",
        "recipient-country",
        "recipient-region",
        "location",
        "location/location-type",
        "location/name",
        "location/description",
        "location/administrative",
        "location/coordinates",
        "location/gazetteer-entry",
        "budget",
        "budget/period-start",
        "budget/period-end",
        "budget/value",
        "planned-disbursement",
        "planned-disbursement/period-start",
        "planned-disbursement/period-end",
        "planned-disbursement/value",
        "activity-website",
        "collaboration-type",
        "policy-marker",
        "transaction",
        "transaction/value",
        "transaction/description",
        "transaction/transaction-type",
        "transaction/provider-org",
        "transaction/receiver-org",
        "transaction/transaction-date",
        "transaction/flow-type",
        "transaction/aid-type",
        "transaction/finance-type",
        "transaction/tied-status",
        "transaction/disbursement-channel",
        "provider-org",
        "receiver-org",
        "document-link",
        "related-activity",
        "legacy-data",
        "conditions",
        "conditions/condition",
        "result",
        "result/indicator", 
        "result/indicator/baseline",
        "result/indicator/period",
        "result/indicator/period/period-start",
        "result/indicator/period/period-end",
        "result/indicator/period/target",
        "result/indicator/period/actual",
        "contact-info/organisation",
        "contact-info/person-name",
        "contact-info/telephone",
        "contact-info/email",
        "contact-info/mailing-address",
        );

$providers = array( "hewlett-foundation"=>"The William and Flora Hewlett Foundation",
                    "hp_12" => "HealthProm",
                    "worldbank" => "The World Bank",
                    "dipr" => "Development Initiatives Poverty Research",
                    "ausaid" => "Australian Agency for International Development",
                    "dfid" => "Department for International Development, United Kingdom",
                    "minbuza_nl" => "Ministry of Foreign Affairs, The Netherlands",
                    "unops" => "UNOPS (United Nations Office for Project Services)",
                    "aa" => "International HIV/AIDS Alliance",
                    "eu" => "European Union",
                    "sida" => "Swedish International Development Cooperation Agency",
                    "ewb_canada" => "Engineers Without Borders Canada",
                    "oxfamgb" => "Oxfam GB",
                    "maec-dgpolde" => "Spain Ministry of Foreign Affairs and Cooperation",
                    "indtrust" => "Indigo Trust",
                    "theglobalfund" => "The Global Fund to Fight AIDS, Tuberculosis and Malaria",
                    "undp" => "United Nations Development Programme",
                    "finland_mfa" => "Finland, Ministry of Foreign Affairs",
                    "asdb" => "Asian Development Bank",
                    "pwyf" => "Publish What You Fund",
                    "nrc" => "Norwegian Refugee Council",
                    "sciaf" => "Scottish Catholic International Aid Fund (SCIAF)",
                    "spark" => "SPARK",
                    "hi" => "Homeless International",
                    "progressio" => "Progressio",
                    "rem" => "Resource Extraction Monitoring",
                    "danida" => "Danida - Danish Ministry of Foreigh Affairs",
                    "gavi" => "GAVI Alliance",
                    "cafod" => "Catholic Agency For Overseas Development",
                    "yipl" => "Young Innovations Pvt. Ltd",
                    "globalgiving" => "GlobalGiving.org",
                    "camfed" => "Camfed International",
                    "mrdf" => "Methodist Relief and Development Fund",
                    "hfhgb" => "Habitat for Humanity Great Britain",
                    "rspb_" => "RSPB",
                    "lead_international" => "LEAD International",
                    "self-help-africa" => "Self Help Africa",
                    "art19" => "Article19",
                    "infid" => "International NGO Forum on Indonesian Development",
                    "transparency-international" => "Transparency International Secretariat",
                    "childhopeuk" => "ChildHope UK ",
                    "evc" => "EveryChild",
                    "afrikids" => "AfriKids",
                    "mapaction" => "MapAction",
                    "theict" => "The International Children's Trust",
                    "basicneeds" => "BasicNeeds",
                    "libertic-520640889" => "Libertic",
                    "icauk" => "ICA:UK",
                    "gb-cc-220949" => "British Red Cross",
                    "buildafrica" => "Build Africa",
                    "tearfund" => "Tearfund",
                    "icn" => "InterClimate Network",
                    "tao-03473165" => "Trust for Africa's Orphans",
                    "waronwant" => "War on Want",
                    "wacc-uk" => "World Association for Christian Communication (UK)",
                    "opportunity-international-uk" => "Opportunity International UK",
                    "ai_1064413" => "African Initiatives",
                    "wvuk" => "World Vision UK",
                    "ffi_publisher" => "Fauna & Flora International",
                    "traidcraft" => "Traidcraft Exchange",
                    "troc" => "Trocaire (Northern Ireland)",
                    "hpa" => "Health Poverty Action",
                    "cic" => "Children in Crisis",
                    "iww_publish" => "Interact Worldwide",
                    "sendacow" => "Send a Cow",
                    "aet" => "Africa Educational Trust",
                    "livingearth12" => "Living Earth Foundation",
                    "fyf" => "Find Your Feet",
                    "concernuk" => "Concern Worldwide UK",
                    "mcs" => "Mercy Corps Scotland",
                    "akfuk73" => "Aga Khan Foundation (United Kingdom)",
                    "spuk" => "Samaritan's Purse UK",
                    "karuna" => "Karuna Trust",
                    "power" => "Power International",
                    "acord" => "agency for cooperation and research in development",
                    "bond" => "Bond",
                    "fm_admin" => "Forests Monitor",
                    "twin-iati" => "Twin",
                    );

?>
