<?php
$available_groups = array("worldbank"=>"World Bank",
                          "eu" => "European Union",
                          "dfid" => "Department For International Development (DFID)",
                          "cafod" => "Catholic Overseas Development Agency (CAFOD)",
                          "undp" => "United Nations Development Programme (UNDP)",
                          "aa" => "Aids Alliance",
                          "hewlett-foundation" => "The William and Flora Hewlett Foundation",
                          "asdb" => "Asian Development Bank",
                          "minbuza_nl" => "Ministry of Foreign Affairs, The Netherlands",
                          "ausaid" => "Australian Agency for International Development",
                          "dipr" => "Development Initiatives Poverty Research",
                          "unops" => "UNOPS (United Nations Office for Project Services)",
                          "ewb_canada" => "EWB Canada",
                          "sida" => "Sweden",
                          "theglobalfund" => "Global Fund",
                          "hivos" => "HIVOS",
                          "aid_register" => "Aid Register Template",
                          "maec-dgpolde" => "Spain Ministry of Foreign Affairs and Cooperation",
                          "finland_mfa" => "Finland",
                          "oxfamgb" => "Oxfam",
                          "indtrust" => "Indigo Trust",
                          "nz" => "NewZealand",
                          "denmark" => "Denmark, Ministry of Foreign Affairs",
                          "transparency_international" => "Transparency International",
                          "gavi" => "GAVI Alliance Secretariat",
                          "rem" => "Resource Extraction Monitoring",
                          "spark" => "SPARK"
                          );
?>                          
